//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Строка заказа.
    /// </summary>
    // *** Start programmer edit section *** (СтрокаЗаказа CustomAttributes)

    // *** End programmer edit section *** (СтрокаЗаказа CustomAttributes)
    [AutoAltered()]
    [Caption("Строка заказа")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СтрокаЗаказаE", new string[] {
            "Сумма as \'Сумма\'",
            "Название as \'Название\'",
            "Товар as \'Товар\'",
            "Товар.Название as \'Название\'"}, Hidden=new string[] {
            "Товар.Название"})]
    [MasterViewDefineAttribute("СтрокаЗаказаE", "Товар", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Название")]
    public class СтрокаЗаказа : ICSSoft.STORMNET.DataObject
    {
        
        private int fво;
        
        private double fСумма;
        
        private string fНазвание;
        
        private IIS.Test6.Товар fТовар;
        
        private IIS.Test6.Заказ fЗаказ;
        
        // *** Start programmer edit section *** (СтрокаЗаказа CustomMembers)

        // *** End programmer edit section *** (СтрокаЗаказа CustomMembers)

        
        /// <summary>
        /// во.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаЗаказа.во CustomAttributes)

        // *** End programmer edit section *** (СтрокаЗаказа.во CustomAttributes)
        private int во
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.во Get start)

                // *** End programmer edit section *** (СтрокаЗаказа.во Get start)
                int result = this.fво;
                // *** Start programmer edit section *** (СтрокаЗаказа.во Get end)

                // *** End programmer edit section *** (СтрокаЗаказа.во Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.во Set start)

                // *** End programmer edit section *** (СтрокаЗаказа.во Set start)
                this.fво = value;
                // *** Start programmer edit section *** (СтрокаЗаказа.во Set end)

                // *** End programmer edit section *** (СтрокаЗаказа.во Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаЗаказа.Название CustomAttributes)

        // *** End programmer edit section *** (СтрокаЗаказа.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Название Get start)

                // *** End programmer edit section *** (СтрокаЗаказа.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (СтрокаЗаказа.Название Get end)

                // *** End programmer edit section *** (СтрокаЗаказа.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Название Set start)

                // *** End programmer edit section *** (СтрокаЗаказа.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (СтрокаЗаказа.Название Set end)

                // *** End programmer edit section *** (СтрокаЗаказа.Название Set end)
            }
        }
        
        /// <summary>
        /// Сумма.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаЗаказа.Сумма CustomAttributes)

        // *** End programmer edit section *** (СтрокаЗаказа.Сумма CustomAttributes)
        public virtual double Сумма
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Сумма Get start)

                // *** End programmer edit section *** (СтрокаЗаказа.Сумма Get start)
                double result = this.fСумма;
                // *** Start programmer edit section *** (СтрокаЗаказа.Сумма Get end)

                // *** End programmer edit section *** (СтрокаЗаказа.Сумма Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Сумма Set start)

                // *** End programmer edit section *** (СтрокаЗаказа.Сумма Set start)
                this.fСумма = value;
                // *** Start programmer edit section *** (СтрокаЗаказа.Сумма Set end)

                // *** End programmer edit section *** (СтрокаЗаказа.Сумма Set end)
            }
        }
        
        /// <summary>
        /// Строка заказа.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаЗаказа.Товар CustomAttributes)

        // *** End programmer edit section *** (СтрокаЗаказа.Товар CustomAttributes)
        [PropertyStorage(new string[] {
                "Товар"})]
        [NotNull()]
        public virtual IIS.Test6.Товар Товар
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Товар Get start)

                // *** End programmer edit section *** (СтрокаЗаказа.Товар Get start)
                IIS.Test6.Товар result = this.fТовар;
                // *** Start programmer edit section *** (СтрокаЗаказа.Товар Get end)

                // *** End programmer edit section *** (СтрокаЗаказа.Товар Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Товар Set start)

                // *** End programmer edit section *** (СтрокаЗаказа.Товар Set start)
                this.fТовар = value;
                // *** Start programmer edit section *** (СтрокаЗаказа.Товар Set end)

                // *** End programmer edit section *** (СтрокаЗаказа.Товар Set end)
            }
        }
        
        /// <summary>
        /// мастеровая ссылка на шапку IIS.Test6.Заказ.
        /// </summary>
        // *** Start programmer edit section *** (СтрокаЗаказа.Заказ CustomAttributes)

        // *** End programmer edit section *** (СтрокаЗаказа.Заказ CustomAttributes)
        [Agregator()]
        [NotNull()]
        [PropertyStorage(new string[] {
                "Заказ"})]
        public virtual IIS.Test6.Заказ Заказ
        {
            get
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Заказ Get start)

                // *** End programmer edit section *** (СтрокаЗаказа.Заказ Get start)
                IIS.Test6.Заказ result = this.fЗаказ;
                // *** Start programmer edit section *** (СтрокаЗаказа.Заказ Get end)

                // *** End programmer edit section *** (СтрокаЗаказа.Заказ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СтрокаЗаказа.Заказ Set start)

                // *** End programmer edit section *** (СтрокаЗаказа.Заказ Set start)
                this.fЗаказ = value;
                // *** Start programmer edit section *** (СтрокаЗаказа.Заказ Set end)

                // *** End programmer edit section *** (СтрокаЗаказа.Заказ Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СтрокаЗаказаE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СтрокаЗаказаE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СтрокаЗаказаE", typeof(IIS.Test6.СтрокаЗаказа));
                }
            }
        }
    }
    
    /// <summary>
    /// Detail array of СтрокаЗаказа.
    /// </summary>
    // *** Start programmer edit section *** (DetailArrayDetailArrayOfСтрокаЗаказа CustomAttributes)

    // *** End programmer edit section *** (DetailArrayDetailArrayOfСтрокаЗаказа CustomAttributes)
    public class DetailArrayOfСтрокаЗаказа : ICSSoft.STORMNET.DetailArray
    {
        
        // *** Start programmer edit section *** (IIS.Test6.DetailArrayOfСтрокаЗаказа members)

        // *** End programmer edit section *** (IIS.Test6.DetailArrayOfСтрокаЗаказа members)

        
        /// <summary>
        /// Construct detail array.
        /// </summary>
        /// <summary>
        /// Returns object with type СтрокаЗаказа by index.
        /// </summary>
        /// <summary>
        /// Adds object with type СтрокаЗаказа.
        /// </summary>
        public DetailArrayOfСтрокаЗаказа(IIS.Test6.Заказ fЗаказ) : 
                base(typeof(СтрокаЗаказа), ((ICSSoft.STORMNET.DataObject)(fЗаказ)))
        {
        }
        
        public IIS.Test6.СтрокаЗаказа this[int index]
        {
            get
            {
                return ((IIS.Test6.СтрокаЗаказа)(this.ItemByIndex(index)));
            }
        }
        
        public virtual void Add(IIS.Test6.СтрокаЗаказа dataobject)
        {
            this.AddObject(((ICSSoft.STORMNET.DataObject)(dataobject)));
        }
    }
}
