//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Test6
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Товар.
    /// </summary>
    // *** Start programmer edit section *** (Товар CustomAttributes)

    // *** End programmer edit section *** (Товар CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ТоварE", new string[] {
            "КодТ as \'Код Т\'",
            "Цена as \'Цена\'",
            "Название as \'Название\'"})]
    [View("ТоварL", new string[] {
            "КодТ as \'Код Т\'",
            "Цена as \'Цена\'",
            "Название as \'Название\'"})]
    public class Товар : ICSSoft.STORMNET.DataObject
    {
        
        private int fКодТ;
        
        private double fЦена;
        
        private string fНазвание;
        
        // *** Start programmer edit section *** (Товар CustomMembers)

        // *** End programmer edit section *** (Товар CustomMembers)

        
        /// <summary>
        /// КодТ.
        /// </summary>
        // *** Start programmer edit section *** (Товар.КодТ CustomAttributes)

        // *** End programmer edit section *** (Товар.КодТ CustomAttributes)
        public virtual int КодТ
        {
            get
            {
                // *** Start programmer edit section *** (Товар.КодТ Get start)

                // *** End programmer edit section *** (Товар.КодТ Get start)
                int result = this.fКодТ;
                // *** Start programmer edit section *** (Товар.КодТ Get end)

                // *** End programmer edit section *** (Товар.КодТ Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.КодТ Set start)

                // *** End programmer edit section *** (Товар.КодТ Set start)
                this.fКодТ = value;
                // *** Start programmer edit section *** (Товар.КодТ Set end)

                // *** End programmer edit section *** (Товар.КодТ Set end)
            }
        }
        
        /// <summary>
        /// Название.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Название CustomAttributes)

        // *** End programmer edit section *** (Товар.Название CustomAttributes)
        [StrLen(255)]
        public virtual string Название
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Название Get start)

                // *** End programmer edit section *** (Товар.Название Get start)
                string result = this.fНазвание;
                // *** Start programmer edit section *** (Товар.Название Get end)

                // *** End programmer edit section *** (Товар.Название Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Название Set start)

                // *** End programmer edit section *** (Товар.Название Set start)
                this.fНазвание = value;
                // *** Start programmer edit section *** (Товар.Название Set end)

                // *** End programmer edit section *** (Товар.Название Set end)
            }
        }
        
        /// <summary>
        /// Цена.
        /// </summary>
        // *** Start programmer edit section *** (Товар.Цена CustomAttributes)

        // *** End programmer edit section *** (Товар.Цена CustomAttributes)
        public virtual double Цена
        {
            get
            {
                // *** Start programmer edit section *** (Товар.Цена Get start)

                // *** End programmer edit section *** (Товар.Цена Get start)
                double result = this.fЦена;
                // *** Start programmer edit section *** (Товар.Цена Get end)

                // *** End programmer edit section *** (Товар.Цена Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Товар.Цена Set start)

                // *** End programmer edit section *** (Товар.Цена Set start)
                this.fЦена = value;
                // *** Start programmer edit section *** (Товар.Цена Set end)

                // *** End programmer edit section *** (Товар.Цена Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ТоварE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварE", typeof(IIS.Test6.Товар));
                }
            }
            
            /// <summary>
            /// "ТоварL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ТоварL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ТоварL", typeof(IIS.Test6.Товар));
                }
            }
        }
    }
}
